/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PlatformReducedUpdateCsvModel } from './platformReducedUpdateCsvModel';
import { BulkImportLogEntry } from './bulkImportLogEntry';


export interface BulkImportUpdateContainerPlatformReducedUpdateCsvModel { 
    bulkImportId?: number;
    lineNumber?: number;
    object?: PlatformReducedUpdateCsvModel;
    attributesToNull?: Array<string>;
    inNameOf?: string;
    bulkImportLogEntry?: BulkImportLogEntry;
}

