/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Permission } from './permission';


export interface ClientCredential { 
    /**
     * Client Id
     */
    clientCredentialId?: string;
    /**
     * Alias for the Client
     */
    alias?: string;
    /**
     * Additional information about the client
     */
    comment?: string;
    /**
     * User permissions
     */
    permissions?: Set<Permission>;
    userId?: string;
}

