/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LineVersionSnapshot } from './lineVersionSnapshot';


export interface ContainerLineVersionSnapshot { 
    objects?: Array<LineVersionSnapshot>;
    totalCount?: number;
}

