/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SectorVersion } from './sectorVersion';


export interface ContainerSectorVersion { 
    objects?: Array<SectorVersion>;
    totalCount?: number;
}

