/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ContactPointType = 'INFORMATION_DESK' | 'TICKET_COUNTER';

export const ContactPointType = {

    InformationDesk: 'INFORMATION_DESK' as ContactPointType,

    TicketCounter: 'TICKET_COUNTER' as ContactPointType
};

