/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TimetableFieldNumber } from './timetableFieldNumber';


export interface ContainerTimetableFieldNumber { 
    objects?: Array<TimetableFieldNumber>;
    totalCount?: number;
}

