/**
 * Atlas API
 * This is the API for all your needs SKI core data<br/><br/>Atlas serves the following applications:<br/><ul><li>line-directory<br/>RestDoc: <a href=\'https://line-directory.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://line-directory.local.app.sbb.ch/static/rest-api.html</a></li><li>service-point-directory<br/>RestDoc: <a href=\'https://service-point-directory.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://service-point-directory.local.app.sbb.ch/static/rest-api.html</a></li><li>business-organisation-directory<br/>RestDoc: <a href=\'https://business-organisation-directory.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://business-organisation-directory.local.app.sbb.ch/static/rest-api.html</a></li><li>workflow<br/>RestDoc: <a href=\'https://workflow.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://workflow.local.app.sbb.ch/static/rest-api.html</a></li><li>export-service-point<br/>RestDoc: <a href=\'https://export-service-point.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://export-service-point.local.app.sbb.ch/static/rest-api.html</a></li><li>user-administration<br/>RestDoc: <a href=\'https://user-administration.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://user-administration.local.app.sbb.ch/static/rest-api.html</a></li><li>import-service-point<br/>RestDoc: <a href=\'https://import-service-point.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://import-service-point.local.app.sbb.ch/static/rest-api.html</a></li><li>prm-directory<br/>RestDoc: <a href=\'https://prm-directory.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://prm-directory.local.app.sbb.ch/static/rest-api.html</a></li></ul>
 *
 * The version of the OpenAPI document: 1.300.0
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CoverageType } from './coverageType';

export interface Coverage {
  /**
   * SLNID
   */
  readonly slnid?: string;
  /**
   * ModelType
   */
  modelType?: Coverage.ModelTypeEnum;
  /**
   * Valid from
   */
  validFrom?: Date;
  /**
   * Valid to
   */
  validTo?: Date;
  coverageType?: CoverageType;
  /**
   * ValidationErrorType
   */
  validationErrorType?: Coverage.ValidationErrorTypeEnum;
}
export namespace Coverage {
  export type ModelTypeEnum = 'LINE' | 'SUBLINE';
  export const ModelTypeEnum = {
    Line: 'LINE' as ModelTypeEnum,
    Subline: 'SUBLINE' as ModelTypeEnum,
  };
  export type ValidationErrorTypeEnum =
    | 'LINE_RANGE_SMALLER_THEN_SUBLINE_RANGE'
    | 'SUBLINE_RANGE_OUTSIDE';
  export const ValidationErrorTypeEnum = {
    LineRangeSmallerThenSublineRange:
      'LINE_RANGE_SMALLER_THEN_SUBLINE_RANGE' as ValidationErrorTypeEnum,
    SublineRangeOutside: 'SUBLINE_RANGE_OUTSIDE' as ValidationErrorTypeEnum,
  };
}
