/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JudgementType } from './judgementType';


export interface Decision { 
    examinantMail: string;
    pinCode: string;
    judgement: JudgementType;
    /**
     * Motivation
     */
    motivation?: string;
    /**
     * Firstname
     */
    firstName: string;
    /**
     * Second
     */
    lastName: string;
    /**
     * Organisation
     */
    organisation: string;
    /**
     * Person Function
     */
    personFunction: string;
}
export namespace Decision {
}


