/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Parameter } from './parameter';


export interface DisplayInfo { 
    /**
     * Errorcode for UI
     */
    code: string;
    /**
     * Parameters for messages
     */
    parameters: Array<Parameter>;
}

