/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DossierStatus = 'ADDED' | 'CANCELED' | 'DOSSIER_BO_CHECK' | 'DOSSIER_CANTON_CHECK' | 'ACCEPTED' | 'REJECTED' | 'MOVED' | 'DISSOLVED';

export const DossierStatus = {

    Added: 'ADDED' as DossierStatus,

    Canceled: 'CANCELED' as DossierStatus,

    DossierBoCheck: 'DOSSIER_BO_CHECK' as DossierStatus,

    DossierCantonCheck: 'DOSSIER_CANTON_CHECK' as DossierStatus,

    Accepted: 'ACCEPTED' as DossierStatus,

    Rejected: 'REJECTED' as DossierStatus,

    Moved: 'MOVED' as DossierStatus,

    Dissolved: 'DISSOLVED' as DossierStatus
};

