/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StopPointPerson } from './stopPointPerson';


export interface EditStopPointWorkflow { 
    /**
     * Official designation of a location that must be used by all recipients
     */
    designationOfficial: string;
    /**
     * Hearing reasons
     */
    workflowComment?: string;
    /**
     * List hearing examinants
     */
    examinants?: Array<StopPointPerson>;
    /**
     * List of cc emails for status of hearing
     */
    ccEmails?: Array<string>;
}

