/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ElementType = 'LINE' | 'SUBLINE';

export const ElementType = {

    Line: 'LINE' as ElementType,

    Subline: 'SUBLINE' as ElementType
};

