/**
 * Atlas API
 * This is the API for all your needs SKI core data<br/><br/>Atlas serves the following applications:<br/>line-directory:1.116.0<br/>business-organisation-directory:1.116.0<br/>workflow:1.116.0<br/>user-administration:1.116.0<br/>
 *
 * The version of the OpenAPI document: 1.116.0
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DisplayInfo } from './displayInfo';

/**
 * List of error details
 */
export interface ErrorDetail {
  /**
   * Errormessage in english for API purposes
   */
  message: string;
  /**
   * Field on which to display the error
   */
  field: string;
  displayInfo: DisplayInfo;
}
