/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DisplayInfo } from './displayInfo';


export interface ErrorDetail { 
    /**
     * Errormessage in english for API purposes
     */
    message: string;
    /**
     * Field on which to display the error
     */
    field: string;
    displayInfo: DisplayInfo;
}

