/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ItemProcessResponseStatus } from './itemProcessResponseStatus';


export interface GeoUpdateItemResult { 
    sloid?: string;
    id?: number;
    message?: string;
    status?: ItemProcessResponseStatus;
}
export namespace GeoUpdateItemResult {
}


