/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type HearingStatus = 'PLANNED' | 'ACTIVE' | 'ARCHIVED';

export const HearingStatus = {

    Planned: 'PLANNED' as HearingStatus,

    Active: 'ACTIVE' as HearingStatus,

    Archived: 'ARCHIVED' as HearingStatus
};

