/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type InfoOpportunityAttributeType = 'TO_BE_COMPLETED' | 'STATIC_VISUAL_INFORMATION' | 'ELECTRONIC_VISUAL_INFORMATION_DEPARTURES' | 'ELECTRONIC_VISUAL_INFORMATION_COMPLETE' | 'ACOUSTIC_INFORMATION' | 'TEXT_TO_SPEECH_DEPARTURES' | 'TEXT_TO_SPEECH_COMPLETE';

export const InfoOpportunityAttributeType = {

    ToBeCompleted: 'TO_BE_COMPLETED' as InfoOpportunityAttributeType,

    StaticVisualInformation: 'STATIC_VISUAL_INFORMATION' as InfoOpportunityAttributeType,

    ElectronicVisualInformationDepartures: 'ELECTRONIC_VISUAL_INFORMATION_DEPARTURES' as InfoOpportunityAttributeType,

    ElectronicVisualInformationComplete: 'ELECTRONIC_VISUAL_INFORMATION_COMPLETE' as InfoOpportunityAttributeType,

    AcousticInformation: 'ACOUSTIC_INFORMATION' as InfoOpportunityAttributeType,

    TextToSpeechDepartures: 'TEXT_TO_SPEECH_DEPARTURES' as InfoOpportunityAttributeType,

    TextToSpeechComplete: 'TEXT_TO_SPEECH_COMPLETE' as InfoOpportunityAttributeType
};

