/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ItemProcessResponseStatus = 'SUCCESS' | 'WARNING' | 'FAILED';

export const ItemProcessResponseStatus = {

    Success: 'SUCCESS' as ItemProcessResponseStatus,

    Warning: 'WARNING' as ItemProcessResponseStatus,

    Failed: 'FAILED' as ItemProcessResponseStatus
};

