/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type LidiElementType = 'ORDERLY' | 'TEMPORARY' | 'OPERATIONAL' | 'DISPOSITION' | 'TECHNICAL' | 'CONCESSION';

export const LidiElementType = {

    Orderly: 'ORDERLY' as LidiElementType,

    Temporary: 'TEMPORARY' as LidiElementType,

    Operational: 'OPERATIONAL' as LidiElementType,

    Disposition: 'DISPOSITION' as LidiElementType,

    Technical: 'TECHNICAL' as LidiElementType,

    Concession: 'CONCESSION' as LidiElementType
};

