/**
 * Atlas API
 * This is the API for all your needs SKI core data<br/><br/>Atlas serves the following applications:<br/><ul><li>line-directory:1.208.0<br/>RestDoc: <a href=\'https://line-directory.dev.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://line-directory.dev.app.sbb.ch/static/rest-api.html</a></li><li>service-point-directory:1.208.0<br/>RestDoc: <a href=\'https://service-point-directory.dev.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://service-point-directory.dev.app.sbb.ch/static/rest-api.html</a></li><li>business-organisation-directory:1.208.0<br/>RestDoc: <a href=\'https://business-organisation-directory.dev.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://business-organisation-directory.dev.app.sbb.ch/static/rest-api.html</a></li><li>workflow:1.208.0<br/>RestDoc: <a href=\'https://workflow.dev.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://workflow.dev.app.sbb.ch/static/rest-api.html</a></li><li>user-administration:1.208.0<br/>RestDoc: <a href=\'https://user-administration.dev.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://user-administration.dev.app.sbb.ch/static/rest-api.html</a></li><li>import-service-point:v0<br/>RestDoc: <a href=\'https://import-service-point.dev.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://import-service-point.dev.app.sbb.ch/static/rest-api.html</a></li></ul>
 *
 * The version of the OpenAPI document: 1.208.0
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Status } from './status';
import { PaymentType } from './paymentType';
import { LineType } from './lineType';
import { WorkflowStatus } from './workflowStatus';

export interface LineVersionSnapshot {
  /**
   * Object creation date
   */
  readonly creationDate?: string;
  /**
   * User creator
   */
  readonly creator?: string;
  /**
   * Last edition date
   */
  readonly editionDate?: string;
  /**
   * User editor
   */
  readonly editor?: string;
  /**
   * Technical identifier
   */
  readonly id?: number;
  /**
   * Workflow Technical identifier
   */
  readonly workflowId: number;
  workflowStatus: WorkflowStatus;
  /**
   * Parent Object identifier
   */
  readonly parentObjectId: number;
  status?: Status;
  lineType: LineType;
  /**
   * SLNID
   */
  readonly slnid?: string;
  paymentType: PaymentType;
  /**
   * Number
   */
  readonly number?: string;
  /**
   * AlternativeName
   */
  readonly alternativeName?: string;
  /**
   * CombinationName
   */
  readonly combinationName?: string;
  /**
   * LongName
   */
  readonly longName?: string;
  /**
   * Color of the font in RGB
   */
  readonly colorFontRgb: string;
  /**
   * Color of the background in RGB
   */
  readonly colorBackRgb: string;
  /**
   * Color of the font in CMYK
   */
  readonly colorFontCmyk: string;
  /**
   * Color of the background in CMYK
   */
  readonly colorBackCmyk: string;
  /**
   * Icon
   */
  readonly icon?: string;
  /**
   * Description
   */
  readonly description?: string;
  /**
   * Valid from
   */
  readonly validFrom: Date;
  /**
   * Valid to
   */
  readonly validTo: Date;
  /**
   * BusinessOrganisation SBOID
   */
  readonly businessOrganisation: string;
  /**
   * Comment
   */
  readonly comment?: string;
  /**
   * Optimistic locking version - instead of ETag HTTP Header (see RFC7232:Section 2.3)
   */
  readonly etagVersion?: number;
}
