/**
 * Atlas API
 * This is the API for all your needs SKI core data<br/><br/>Atlas serves the following applications:<br/>line-directory:0.481.0-SNAPSHOT<br/>business-organisation-directory:0.481.0-SNAPSHOT<br/>
 *
 * The version of the OpenAPI document: 0.481.0-SNAPSHOT
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Status } from './status';
import { PaymentType } from './paymentType';
import { LineType } from './lineType';

export interface LineVersion {
  /**
   * Technical identifier
   */
  readonly id?: number;
  /**
   * SwissLineNumber
   */
  swissLineNumber: string;
  status?: Status;
  lineType: LineType;
  /**
   * SLNID
   */
  readonly slnid?: string;
  paymentType: PaymentType;
  /**
   * Number
   */
  number?: string;
  /**
   * AlternativeName
   */
  alternativeName?: string;
  /**
   * CombinationName
   */
  combinationName?: string;
  /**
   * LongName
   */
  longName?: string;
  /**
   * Color of the font in RGB
   */
  colorFontRgb: string;
  /**
   * Color of the background in RGB
   */
  colorBackRgb: string;
  /**
   * Color of the font in CMYK
   */
  colorFontCmyk: string;
  /**
   * Color of the background in CMYK
   */
  colorBackCmyk: string;
  /**
   * Icon
   */
  icon?: string;
  /**
   * Description
   */
  description?: string;
  /**
   * Valid from
   */
  validFrom: Date;
  /**
   * Valid to
   */
  validTo: Date;
  /**
   * BusinessOrganisation
   */
  businessOrganisation: string;
  /**
   * Comment
   */
  comment?: string;
  /**
   * Optimistic locking version - instead of ETag HTTP Header (see RFC7232:Section 2.3)
   */
  etagVersion?: number;
}
