/**
 * Atlas API
 * This is the API for all your needs SKI core data<br/><br/>Atlas serves the following applications:<br/>line-directory:1.39.0-SNAPSHOT<br/>business-organisation-directory:1.39.0-SNAPSHOT<br/>user-administration:1.39.0-SNAPSHOT<br/>
 *
 * The version of the OpenAPI document: 1.39.0-SNAPSHOT
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * LineType
 */
export type LineType = 'ORDERLY' | 'TEMPORARY' | 'OPERATIONAL';

export const LineType = {
  Orderly: 'ORDERLY' as LineType,
  Temporary: 'TEMPORARY' as LineType,
  Operational: 'OPERATIONAL' as LineType,
};
