/**
 * Atlas API
 * This is the API for all your needs SKI core data<br/><br/>Atlas serves the following applications:<br/><ul><li>line-directory<br/>RestDoc: <a href=\'https://line-directory.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://line-directory.local.app.sbb.ch/static/rest-api.html</a></li><li>service-point-directory<br/>RestDoc: <a href=\'https://service-point-directory.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://service-point-directory.local.app.sbb.ch/static/rest-api.html</a></li><li>business-organisation-directory<br/>RestDoc: <a href=\'https://business-organisation-directory.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://business-organisation-directory.local.app.sbb.ch/static/rest-api.html</a></li><li>workflow<br/>RestDoc: <a href=\'https://workflow.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://workflow.local.app.sbb.ch/static/rest-api.html</a></li><li>export-service-point<br/>RestDoc: <a href=\'https://export-service-point.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://export-service-point.local.app.sbb.ch/static/rest-api.html</a></li><li>user-administration<br/>RestDoc: <a href=\'https://user-administration.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://user-administration.local.app.sbb.ch/static/rest-api.html</a></li><li>import-service-point<br/>RestDoc: <a href=\'https://import-service-point.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://import-service-point.local.app.sbb.ch/static/rest-api.html</a></li><li>prm-directory<br/>RestDoc: <a href=\'https://prm-directory.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://prm-directory.local.app.sbb.ch/static/rest-api.html</a></li></ul>
 *
 * The version of the OpenAPI document: 1.436.0
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Status } from './status';
import { LineVersionWorkflow } from './lineVersionWorkflow';
import { PaymentType } from './paymentType';
import { LineType } from './lineType';

export interface LineVersion {
  /**
   * Object creation date
   */
  readonly creationDate?: string;
  /**
   * User creator
   */
  readonly creator?: string;
  /**
   * Last edition date
   */
  readonly editionDate?: string;
  /**
   * User editor
   */
  readonly editor?: string;
  /**
   * Technical identifier
   */
  readonly id?: number;
  /**
   * SwissLineNumber
   */
  swissLineNumber: string;
  status?: Status;
  lineType: LineType;
  /**
   * SLNID
   */
  readonly slnid?: string;
  paymentType: PaymentType;
  /**
   * Number
   */
  number?: string;
  /**
   * AlternativeName
   */
  alternativeName?: string;
  /**
   * CombinationName
   */
  combinationName?: string;
  /**
   * LongName
   */
  longName?: string;
  /**
   * Color of the font in RGB
   */
  colorFontRgb: string;
  /**
   * Color of the background in RGB
   */
  colorBackRgb: string;
  /**
   * Color of the font in CMYK
   */
  colorFontCmyk: string;
  /**
   * Color of the background in CMYK
   */
  colorBackCmyk: string;
  /**
   * Icon
   */
  icon?: string;
  /**
   * Description
   */
  description?: string;
  /**
   * Valid from
   */
  validFrom: Date;
  /**
   * Valid to
   */
  validTo: Date;
  /**
   * BusinessOrganisation SBOID
   */
  businessOrganisation: string;
  /**
   * Comment
   */
  comment?: string;
  /**
   * Optimistic locking version - instead of ETag HTTP Header (see RFC7232:Section 2.3)
   */
  etagVersion?: number;
  /**
   * Workflows related to the line version
   */
  readonly lineVersionWorkflows?: Set<LineVersionWorkflow>;
}
