/**
 * Atlas API
 * This is the API for all your needs SKI core data<br/><br/>Atlas serves the following applications:<br/><ul><li>line-directory:1.204.0<br/>RestDoc: <a href=\'https://line-directory.dev.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://line-directory.dev.app.sbb.ch/static/rest-api.html</a></li><li>service-point-directory:1.204.0<br/>RestDoc: <a href=\'https://service-point-directory.dev.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://service-point-directory.dev.app.sbb.ch/static/rest-api.html</a></li><li>business-organisation-directory:1.204.0<br/>RestDoc: <a href=\'https://business-organisation-directory.dev.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://business-organisation-directory.dev.app.sbb.ch/static/rest-api.html</a></li><li>workflow:1.204.0<br/>RestDoc: <a href=\'https://workflow.dev.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://workflow.dev.app.sbb.ch/static/rest-api.html</a></li><li>user-administration:1.204.0<br/>RestDoc: <a href=\'https://user-administration.dev.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://user-administration.dev.app.sbb.ch/static/rest-api.html</a></li><li>import-service-point:v0<br/>RestDoc: <a href=\'https://import-service-point.dev.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://import-service-point.dev.app.sbb.ch/static/rest-api.html</a></li></ul>
 *
 * The version of the OpenAPI document: 1.204.0
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Means of transport. Indicates for which means of transport a stop is intended/equipped. Mandatory for StopPoints
 */
export type MeanOfTransport =
  | 'TRAIN'
  | 'BUS'
  | 'TRAM'
  | 'BOAT'
  | 'CABLE_CAR'
  | 'CHAIRLIFT'
  | 'CABLE_RAILWAY'
  | 'RACK_RAILWAY'
  | 'METRO'
  | 'ELEVATOR'
  | 'UNKNOWN';

export const MeanOfTransport = {
  Train: 'TRAIN' as MeanOfTransport,
  Bus: 'BUS' as MeanOfTransport,
  Tram: 'TRAM' as MeanOfTransport,
  Boat: 'BOAT' as MeanOfTransport,
  CableCar: 'CABLE_CAR' as MeanOfTransport,
  Chairlift: 'CHAIRLIFT' as MeanOfTransport,
  CableRailway: 'CABLE_RAILWAY' as MeanOfTransport,
  RackRailway: 'RACK_RAILWAY' as MeanOfTransport,
  Metro: 'METRO' as MeanOfTransport,
  Elevator: 'ELEVATOR' as MeanOfTransport,
  Unknown: 'UNKNOWN' as MeanOfTransport,
};
