/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PermissionRestriction } from './permissionRestriction';
import { PermissionRestrictionType } from './permissionRestrictionType';


export interface NovaTerminationVotePermissionRestrictionModel extends PermissionRestriction { 
}
export namespace NovaTerminationVotePermissionRestrictionModel {
}


