/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type OperatingPointType = 'INVENTORY_POINT' | 'SYSTEM_OPERATING_POINT' | 'RAILNET_POINT';

export const OperatingPointType = {

    InventoryPoint: 'INVENTORY_POINT' as OperatingPointType,

    SystemOperatingPoint: 'SYSTEM_OPERATING_POINT' as OperatingPointType,

    RailnetPoint: 'RAILNET_POINT' as OperatingPointType
};

