/**
 * Atlas API
 * This is the API for all your needs SKI core data<br/><br/>Atlas serves the following applications:<br/><ul><li>line-directory<br/>RestDoc: <a href=\'https://line-directory.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://line-directory.local.app.sbb.ch/static/rest-api.html</a></li><li>service-point-directory<br/>RestDoc: <a href=\'https://service-point-directory.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://service-point-directory.local.app.sbb.ch/static/rest-api.html</a></li><li>business-organisation-directory<br/>RestDoc: <a href=\'https://business-organisation-directory.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://business-organisation-directory.local.app.sbb.ch/static/rest-api.html</a></li><li>workflow<br/>RestDoc: <a href=\'https://workflow.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://workflow.local.app.sbb.ch/static/rest-api.html</a></li><li>export-service-point<br/>RestDoc: <a href=\'https://export-service-point.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://export-service-point.local.app.sbb.ch/static/rest-api.html</a></li><li>user-administration<br/>RestDoc: <a href=\'https://user-administration.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://user-administration.local.app.sbb.ch/static/rest-api.html</a></li><li>import-service-point<br/>RestDoc: <a href=\'https://import-service-point.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://import-service-point.local.app.sbb.ch/static/rest-api.html</a></li><li>prm-directory<br/>RestDoc: <a href=\'https://prm-directory.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://prm-directory.local.app.sbb.ch/static/rest-api.html</a></li></ul>
 *
 * The version of the OpenAPI document: 1.436.0
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * OperatingPointTechnicalTimetableType, all service points relevant for timetable planning and publication. At most one of OperatingPointTechnicalTimetableType, OperatingPointTrafficPointType may be set
 */
export type OperatingPointTechnicalTimetableType = 'PROPERTY_LINE' | 'INVESTMENT_LOCATIONS_OPERATING_POINT' | 'COUNTRY_BORDER' | 'UNKNOWN' | 'OPERATING_POINT_BUS' | 'TURNING_LOOP' | 'ASSIGNED_OPERATING_POINT' | 'BLOCKING_POINT' | 'END_OF_TRACK' | 'LANE_SEPARATION' | 'INTERSECTION' | 'CONNECTING_POINT' | 'LANE_CHANGE' | 'BRANCH' | 'SERVICE_STATION' | 'ERROR_PROFILE' | 'EX_STOP_POINT' | 'ROUTE_SPEED_CHANGE';

export const OperatingPointTechnicalTimetableType = {
    PropertyLine: 'PROPERTY_LINE' as OperatingPointTechnicalTimetableType,
    InvestmentLocationsOperatingPoint: 'INVESTMENT_LOCATIONS_OPERATING_POINT' as OperatingPointTechnicalTimetableType,
    CountryBorder: 'COUNTRY_BORDER' as OperatingPointTechnicalTimetableType,
    Unknown: 'UNKNOWN' as OperatingPointTechnicalTimetableType,
    OperatingPointBus: 'OPERATING_POINT_BUS' as OperatingPointTechnicalTimetableType,
    TurningLoop: 'TURNING_LOOP' as OperatingPointTechnicalTimetableType,
    AssignedOperatingPoint: 'ASSIGNED_OPERATING_POINT' as OperatingPointTechnicalTimetableType,
    BlockingPoint: 'BLOCKING_POINT' as OperatingPointTechnicalTimetableType,
    EndOfTrack: 'END_OF_TRACK' as OperatingPointTechnicalTimetableType,
    LaneSeparation: 'LANE_SEPARATION' as OperatingPointTechnicalTimetableType,
    Intersection: 'INTERSECTION' as OperatingPointTechnicalTimetableType,
    ConnectingPoint: 'CONNECTING_POINT' as OperatingPointTechnicalTimetableType,
    LaneChange: 'LANE_CHANGE' as OperatingPointTechnicalTimetableType,
    Branch: 'BRANCH' as OperatingPointTechnicalTimetableType,
    ServiceStation: 'SERVICE_STATION' as OperatingPointTechnicalTimetableType,
    ErrorProfile: 'ERROR_PROFILE' as OperatingPointTechnicalTimetableType,
    ExStopPoint: 'EX_STOP_POINT' as OperatingPointTechnicalTimetableType,
    RouteSpeedChange: 'ROUTE_SPEED_CHANGE' as OperatingPointTechnicalTimetableType
};

