/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type OperatingPointTrafficPointType = 'TARIFF_POINT';

export const OperatingPointTrafficPointType = {

    TariffPoint: 'TARIFF_POINT' as OperatingPointTrafficPointType
};

