/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PermissionRestrictionType } from './permissionRestrictionType';


export interface PermissionRestrictionObject { 
    type?: PermissionRestrictionType;
    valueAsString?: string;
}
export namespace PermissionRestrictionObject {
}


