/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type PermissionRestrictionType = 'BUSINESS_ORGANISATION' | 'CANTON' | 'COUNTRY' | 'BULK_IMPORT' | 'INFO_PLUS_TERMINATION_VOTE' | 'NOVA_TERMINATION_VOTE';

export const PermissionRestrictionType = {

    BusinessOrganisation: 'BUSINESS_ORGANISATION' as PermissionRestrictionType,

    Canton: 'CANTON' as PermissionRestrictionType,

    Country: 'COUNTRY' as PermissionRestrictionType,

    BulkImport: 'BULK_IMPORT' as PermissionRestrictionType,

    InfoPlusTerminationVote: 'INFO_PLUS_TERMINATION_VOTE' as PermissionRestrictionType,

    NovaTerminationVote: 'NOVA_TERMINATION_VOTE' as PermissionRestrictionType
};

