/**
 * Atlas API
 * This is the API for all your needs SKI core data<br/><br/>Atlas serves the following applications:<br/><ul><li>line-directory<br/>RestDoc: <a href=\'https://line-directory.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://line-directory.local.app.sbb.ch/static/rest-api.html</a></li><li>service-point-directory<br/>RestDoc: <a href=\'https://service-point-directory.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://service-point-directory.local.app.sbb.ch/static/rest-api.html</a></li><li>business-organisation-directory<br/>RestDoc: <a href=\'https://business-organisation-directory.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://business-organisation-directory.local.app.sbb.ch/static/rest-api.html</a></li><li>workflow<br/>RestDoc: <a href=\'https://workflow.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://workflow.local.app.sbb.ch/static/rest-api.html</a></li><li>export-service-point<br/>RestDoc: <a href=\'https://export-service-point.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://export-service-point.local.app.sbb.ch/static/rest-api.html</a></li><li>user-administration<br/>RestDoc: <a href=\'https://user-administration.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://user-administration.local.app.sbb.ch/static/rest-api.html</a></li><li>import-service-point<br/>RestDoc: <a href=\'https://import-service-point.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://import-service-point.local.app.sbb.ch/static/rest-api.html</a></li><li>prm-directory<br/>RestDoc: <a href=\'https://prm-directory.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://prm-directory.local.app.sbb.ch/static/rest-api.html</a></li></ul>
 *
 * The version of the OpenAPI document: 1.532.0
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PlatformCsvModel {
  VALID_FROM?: Date;
  VALID_TO?: Date;
  ADD_DATE?: string;
  ADDED_BY?: string;
  MODIFIED_DATE?: string;
  MODIFIED_BY?: string;
  SLOID?: string;
  DIDOK_CODE?: number;
  STATUS?: number;
  BOARDING_DEVICE?: number;
  COMPL_ACCESS_INFO?: string;
  COMPL_INFOS?: string;
  CONTRASTING_AREAS?: number;
  DYNAMIC_AUDIO?: number;
  DYNAMIC_VISUAL?: number;
  HEIGHT?: number;
  INCLINATION?: number;
  INCLINATION_LONG?: number;
  INCLINATION_WIDTH?: number;
  INFO_BLINDS?: string;
  LEVEL_ACCESS_WHEELCHAIR?: number;
  PARTIAL_ELEV?: number;
  SUPERELEVATION?: number;
  TACTILE_SYSTEMS?: number;
  VEHICLE_ACCESS?: number;
  WHEELCHAIR_AREA_LENGTH?: number;
  WHEELCHAIR_AREA_WIDTH?: number;
  DS_SLOID?: string;
}
