/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Status } from './status';
import { ServicePointNumber } from './servicePointNumber';
import { BooleanOptionalAttributeType } from './booleanOptionalAttributeType';
import { VehicleAccessAttributeType } from './vehicleAccessAttributeType';
import { BasicAttributeType } from './basicAttributeType';
import { InfoOpportunityAttributeType } from './infoOpportunityAttributeType';
import { BoardingDeviceAttributeType } from './boardingDeviceAttributeType';


export interface ReadPlatformVersion { 
    /**
     * Object creation date
     */
    readonly creationDate?: string;
    /**
     * User creator
     */
    readonly creator?: string;
    /**
     * Last edition date
     */
    readonly editionDate?: string;
    /**
     * User editor
     */
    readonly editor?: string;
    status?: Status;
    /**
     * This ID helps identify versions of a prm object in the use case front end and/or update. This ID can be deleted if the version is no longer present. Do not use this ID to map your object to a prm object. To do this, use the sloid or parentServicePointSloid in combination with the data range (valid from/valid until). 
     */
    readonly id?: number;
    /**
     * Valid from
     */
    validFrom: Date;
    /**
     * Valid to
     */
    validTo: Date;
    /**
     * Optimistic locking version - instead of ETag HTTP Header (see RFC7232:Section 2.3)
     */
    etagVersion?: number;
    /**
     * Unique code for locations that is used in customer information. The structure is described in the “Swiss Location ID” specification, chapter 4.2. The document is available here: https://transportdatamanagement.ch/standards/
     */
    sloid?: string;
    /**
     * Parent Service Point Sloid: Unique code for locations that is used in customer information. The structure is described in the “Swiss Location ID” specification, chapter 4.2. The document is available here: https://transportdatamanagement.ch/standards/
     */
    parentServicePointSloid: string;
    boardingDevice?: BoardingDeviceAttributeType;
    /**
     * Information on access to transport
     */
    adviceAccessInfo?: string;
    /**
     * Additional Information
     */
    additionalInformation?: string;
    shuttle?: BooleanOptionalAttributeType;
    contrastingAreas?: BooleanOptionalAttributeType;
    dynamicAudio?: BasicAttributeType;
    dynamicVisual?: BasicAttributeType;
    /**
     * Height [cm]
     */
    height?: number;
    /**
     * Cross-platform slope [%]
     */
    inclination?: number;
    /**
     * Longitudinal inclination of the holding edge [%]
     */
    inclinationLongitudinal?: number;
    /**
     * Platform longitudinal inclination [%]
     */
    inclinationWidth?: number;
    /**
     * Information options
     */
    infoOpportunities?: Array<InfoOpportunityAttributeType>;
    levelAccessWheelchair?: BasicAttributeType;
    partialElevation?: boolean;
    /**
     * Track superelevation value [mm]
     */
    superelevation?: number;
    tactileSystem?: BooleanOptionalAttributeType;
    attentionField?: BooleanOptionalAttributeType;
    vehicleAccess?: VehicleAccessAttributeType;
    /**
     * Wheelchair Area Length [mm]
     */
    wheelchairAreaLength?: number;
    /**
     * Wheelchair Area Width [mm]
     */
    wheelchairAreaWidth?: number;
    number: ServicePointNumber;
}
export namespace ReadPlatformVersion {
}


