/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ReferencePointElementType = 'PLATFORM' | 'CONTACT_POINT' | 'TOILET' | 'PARKING_LOT';

export const ReferencePointElementType = {

    Platform: 'PLATFORM' as ReferencePointElementType,

    ContactPoint: 'CONTACT_POINT' as ReferencePointElementType,

    Toilet: 'TOILET' as ReferencePointElementType,

    ParkingLot: 'PARKING_LOT' as ReferencePointElementType
};

