/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ServicePointSearchResult { 
    /**
     * DiDok-Number formerly known as UIC-Code, combination of uicCountryCode and numberShort.
     */
    number?: number;
    /**
     * Official designation of a location that must be used by all recipients
     */
    designationOfficial?: string;
    /**
     * Unique key for service points which is used in the customer information.
     */
    sloid?: string;
}

