/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CoordinatePair } from './coordinatePair';
import { SpatialReference } from './spatialReference';
import { SwissLocation } from './swissLocation';


/**
 * Service point geolocation
 */
export interface ServicePointGeolocation { 
    spatialReference: SpatialReference;
    lv95: CoordinatePair;
    wgs84: CoordinatePair;
    lv03: CoordinatePair;
    /**
     * Height of the coordinate point
     */
    height?: number;
    swissLocation?: SwissLocation;
    /**
     * ISO 2 abbreviation of the country, based on coordinates
     */
    readonly isoCountryCode?: string;
}
export namespace ServicePointGeolocation {
}


