/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OperatingPointTrafficPointType } from './operatingPointTrafficPointType';
import { StopPointType } from './stopPointType';
import { Category } from './category';
import { OperatingPointType } from './operatingPointType';
import { SpatialReference } from './spatialReference';
import { OperatingPointTechnicalTimetableType } from './operatingPointTechnicalTimetableType';


export interface ServicePointUpdateCsvModel { 
    sloid?: string;
    number?: number;
    validFrom?: Date;
    validTo?: Date;
    designationOfficial?: string;
    designationLong?: string;
    stopPointType?: StopPointType;
    freightServicePoint?: boolean;
    operatingPointType?: OperatingPointType;
    operatingPointTechnicalTimetableType?: OperatingPointTechnicalTimetableType;
    meansOfTransport?: Set<ServicePointUpdateCsvModel.MeansOfTransportEnum>;
    categories?: Set<Category>;
    operatingPointTrafficPointType?: OperatingPointTrafficPointType;
    sortCodeOfDestinationStation?: string;
    businessOrganisation?: string;
    east?: number;
    north?: number;
    spatialReference?: SpatialReference;
    height?: number;
}
export namespace ServicePointUpdateCsvModel {
    export type MeansOfTransportEnum = 'TRAIN' | 'BUS' | 'TRAM' | 'BOAT' | 'CABLE_CAR' | 'CHAIRLIFT' | 'CABLE_RAILWAY' | 'RACK_RAILWAY' | 'METRO' | 'ELEVATOR' | 'UNKNOWN';
    export const MeansOfTransportEnum = {
        Train: 'TRAIN' as MeansOfTransportEnum,
        Bus: 'BUS' as MeansOfTransportEnum,
        Tram: 'TRAM' as MeansOfTransportEnum,
        Boat: 'BOAT' as MeansOfTransportEnum,
        CableCar: 'CABLE_CAR' as MeansOfTransportEnum,
        Chairlift: 'CHAIRLIFT' as MeansOfTransportEnum,
        CableRailway: 'CABLE_RAILWAY' as MeansOfTransportEnum,
        RackRailway: 'RACK_RAILWAY' as MeansOfTransportEnum,
        Metro: 'METRO' as MeansOfTransportEnum,
        Elevator: 'ELEVATOR' as MeansOfTransportEnum,
        Unknown: 'UNKNOWN' as MeansOfTransportEnum
    };
}


