/**
 * Atlas API
 * This is the API for all your needs SKI core data<br/><br/>Atlas serves the following applications:<br/><ul><li>line-directory:1.204.0<br/>RestDoc: <a href=\'https://line-directory.dev.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://line-directory.dev.app.sbb.ch/static/rest-api.html</a></li><li>service-point-directory:1.204.0<br/>RestDoc: <a href=\'https://service-point-directory.dev.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://service-point-directory.dev.app.sbb.ch/static/rest-api.html</a></li><li>business-organisation-directory:1.204.0<br/>RestDoc: <a href=\'https://business-organisation-directory.dev.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://business-organisation-directory.dev.app.sbb.ch/static/rest-api.html</a></li><li>workflow:1.204.0<br/>RestDoc: <a href=\'https://workflow.dev.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://workflow.dev.app.sbb.ch/static/rest-api.html</a></li><li>user-administration:1.204.0<br/>RestDoc: <a href=\'https://user-administration.dev.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://user-administration.dev.app.sbb.ch/static/rest-api.html</a></li><li>import-service-point:v0<br/>RestDoc: <a href=\'https://import-service-point.dev.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://import-service-point.dev.app.sbb.ch/static/rest-api.html</a></li></ul>
 *
 * The version of the OpenAPI document: 1.204.0
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ServicePointNumber {
  /**
   * DiDok-Number formerly known as UIC-Code, combination of uicCountryCode and numberShort. Size: 7
   */
  number: number;
  /**
   * UicCountryCode, Indicates which country allocated the service point number and is to be interpreted organisationally, not territorially.
   */
  uicCountryCode: number;
  /**
   * Calculated value formed from the numberShort. Range: 0-9
   */
  checkDigit: number;
  /**
   * NumberShort - 5 chars identifying number. Range: 1-99.999
   */
  numberShort: number;
}
