/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type StandardAttributeType = 'TO_BE_COMPLETED' | 'YES' | 'NO' | 'NOT_APPLICABLE' | 'PARTIALLY';

export const StandardAttributeType = {

    ToBeCompleted: 'TO_BE_COMPLETED' as StandardAttributeType,

    Yes: 'YES' as StandardAttributeType,

    No: 'NO' as StandardAttributeType,

    NotApplicable: 'NOT_APPLICABLE' as StandardAttributeType,

    Partially: 'PARTIALLY' as StandardAttributeType
};

