/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StartTerminationStopPointAddWorkflow { 
    /**
     * Service Point version id
     */
    versionId: number;
    /**
     * Unique code for locations that is used in customer information. The structure is described in the “Swiss Location ID” specification, chapter 4.2. The document is available here. https://transportdatamanagement.ch/standards/
     */
    sloid: string;
    /**
     * Applicant mail
     */
    applicantMail: string;
    /**
     * Termination Date defined by Business Organisation managing the Stop Point
     */
    boTerminationDate?: Date;
    /**
     * Workflow comment
     */
    workflowComment?: string;
}

