/**
 * Atlas API
 * This is the API for all your needs SKI core data<br/><br/>Atlas serves the following applications:<br/><ul><li>line-directory:1.229.0<br/>RestDoc: <a href=\'https://line-directory.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://line-directory.local.app.sbb.ch/static/rest-api.html</a></li><li>service-point-directory:1.229.0<br/>RestDoc: <a href=\'https://service-point-directory.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://service-point-directory.local.app.sbb.ch/static/rest-api.html</a></li><li>business-organisation-directory:1.229.0<br/>RestDoc: <a href=\'https://business-organisation-directory.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://business-organisation-directory.local.app.sbb.ch/static/rest-api.html</a></li><li>workflow:1.229.0<br/>RestDoc: <a href=\'https://workflow.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://workflow.local.app.sbb.ch/static/rest-api.html</a></li><li>user-administration:1.229.0<br/>RestDoc: <a href=\'https://user-administration.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://user-administration.local.app.sbb.ch/static/rest-api.html</a></li><li>import-service-point:v0<br/>RestDoc: <a href=\'https://import-service-point.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://import-service-point.local.app.sbb.ch/static/rest-api.html</a></li></ul>
 *
 * The version of the OpenAPI document: 1.229.0
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Current status
 */
export type StatementStatus =
  | 'RECEIVED'
  | 'IN_REVIEW'
  | 'ACCEPTED'
  | 'PARTLY_IMPLEMENTED'
  | 'NOTED'
  | 'REJECTED'
  | 'MOVED'
  | 'JUNK'
  | 'REVOKED';

export const StatementStatus = {
  Received: 'RECEIVED' as StatementStatus,
  InReview: 'IN_REVIEW' as StatementStatus,
  Accepted: 'ACCEPTED' as StatementStatus,
  PartlyImplemented: 'PARTLY_IMPLEMENTED' as StatementStatus,
  Noted: 'NOTED' as StatementStatus,
  Rejected: 'REJECTED' as StatementStatus,
  Moved: 'MOVED' as StatementStatus,
  Junk: 'JUNK' as StatementStatus,
  Revoked: 'REVOKED' as StatementStatus,
};
