/**
 * Atlas API
 * This is the API for all your needs SKI core data<br/><br/>Atlas serves the following applications:<br/><ul><li>line-directory<br/>RestDoc: <a href=\'https://line-directory.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://line-directory.local.app.sbb.ch/static/rest-api.html</a></li><li>service-point-directory<br/>RestDoc: <a href=\'https://service-point-directory.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://service-point-directory.local.app.sbb.ch/static/rest-api.html</a></li><li>business-organisation-directory<br/>RestDoc: <a href=\'https://business-organisation-directory.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://business-organisation-directory.local.app.sbb.ch/static/rest-api.html</a></li><li>workflow<br/>RestDoc: <a href=\'https://workflow.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://workflow.local.app.sbb.ch/static/rest-api.html</a></li><li>export-service-point<br/>RestDoc: <a href=\'https://export-service-point.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://export-service-point.local.app.sbb.ch/static/rest-api.html</a></li><li>user-administration<br/>RestDoc: <a href=\'https://user-administration.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://user-administration.local.app.sbb.ch/static/rest-api.html</a></li><li>import-service-point<br/>RestDoc: <a href=\'https://import-service-point.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://import-service-point.local.app.sbb.ch/static/rest-api.html</a></li><li>prm-directory<br/>RestDoc: <a href=\'https://prm-directory.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://prm-directory.local.app.sbb.ch/static/rest-api.html</a></li></ul>
 *
<<<<<<< HEAD
 * The version of the OpenAPI document: 1.556.0
=======
 * The version of the OpenAPI document: 1.436.0
>>>>>>> ec4ca2d61 (ATLAS-1353: Overview Table)
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface StopPointCsvModel {
  VALID_FROM?: Date;
  VALID_TO?: Date;
  ADD_DATE?: string;
  ADDED_BY?: string;
  MODIFIED_DATE?: string;
  MODIFIED_BY?: string;
  DIDOK_CODE?: number;
  DS_SLOID?: string;
  ADDRESS?: string;
  ZIP_CODE?: string;
  CITY?: string;
  ALTERNATIVE_TRANSPORT?: number;
  ALT_TRANSPORT_CONDITION?: string;
  ASSISTANCE_AVAILABILITY?: number;
  ASSISTANCE_CONDITION?: string;
  ASSISTANCE_SERVICE?: number;
  AUDIO_TICK_MACH?: number;
  COMP_INFOS?: string;
  DYNAMIC_AUDIO_SYS?: number;
  DYNAMIC_OPTIC_SYS?: number;
  FREE_TEXT?: string;
  INFO_TICK_MACH?: string;
  INTEROPERABLE?: number;
  ASSISTANCE_REQS_FULFILLED?: number;
  STATUS?: number;
  TICKET_MACHINE?: number;
  URL?: string;
  TRANSPORTATION_MEANS?: string;
  VISUAL_INFOS?: number;
  WHEELCHAIR_TICK_MACH?: number;
}
