/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Status } from './status';
import { SublineConcessionType } from './sublineConcessionType';


export interface SublineVersionV2 { 
    /**
     * Object creation date
     */
    readonly creationDate?: string;
    /**
     * User creator
     */
    readonly creator?: string;
    /**
     * Last edition date
     */
    readonly editionDate?: string;
    /**
     * User editor
     */
    readonly editor?: string;
    status?: Status;
    /**
     * This ID helps identify versions of a subline in the use case front end and/or update. This ID can be deleted if the version is no longer present. Do not use this ID to map your object to a subline. To do this, use the slnid in combination with the data range (valid from/valid until). 
     */
    readonly id?: number;
    /**
     * SwissSublineNumber
     */
    swissSublineNumber?: string;
    /**
     * SLNID of main line
     */
    mainlineSlnid: string;
    /**
     * SLNID
     */
    readonly slnid?: string;
    /**
     * Description
     */
    description: string;
    /**
     * LongName
     */
    longName?: string;
    /**
     * BusinessOrganisation SBOID
     */
    readonly businessOrganisation: string;
    /**
     * Valid from
     */
    validFrom: Date;
    /**
     * Valid to
     */
    validTo: Date;
    /**
     * Optimistic locking version - instead of ETag HTTP Header (see RFC7232:Section 2.3)
     */
    etagVersion?: number;
    sublineConcessionType?: SublineConcessionType;
}
export namespace SublineVersionV2 {
}


