/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type SublineConcessionType = 'FEDERALLY_LICENSED_OR_APPROVED_LINE' | 'VARIANT_OF_A_LICENSED_LINE' | 'CANTONALLY_APPROVED_LINE' | 'RIGHT_FREE_LINE' | 'NOT_LICENSED_UNPUBLISHED_LINE' | 'LINE_ABROAD';

export const SublineConcessionType = {

    FederallyLicensedOrApprovedLine: 'FEDERALLY_LICENSED_OR_APPROVED_LINE' as SublineConcessionType,

    VariantOfALicensedLine: 'VARIANT_OF_A_LICENSED_LINE' as SublineConcessionType,

    CantonallyApprovedLine: 'CANTONALLY_APPROVED_LINE' as SublineConcessionType,

    RightFreeLine: 'RIGHT_FREE_LINE' as SublineConcessionType,

    NotLicensedUnpublishedLine: 'NOT_LICENSED_UNPUBLISHED_LINE' as SublineConcessionType,

    LineAbroad: 'LINE_ABROAD' as SublineConcessionType
};

