/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SwissCanton } from './swissCanton';
import { LocalityMunicipality } from './localityMunicipality';
import { Canton } from './canton';
import { District } from './district';


export interface SwissLocation { 
    canton?: SwissCanton;
    cantonInformation?: Canton;
    district?: District;
    localityMunicipality?: LocalityMunicipality;
}
export namespace SwissLocation {
}


