/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TimetableHearingStatementSenderV2 { 
    /**
     * First Name
     */
    firstName?: string;
    /**
     * Last Name
     */
    lastName?: string;
    /**
     * Organisation
     */
    organisation?: string;
    /**
     * Street
     */
    street?: string;
    /**
     * ZIP Code
     */
    zip?: number;
    /**
     * City
     */
    city?: string;
    /**
     * E-Mail addresses
     */
    emails?: Set<string>;
}

