/**
 * Atlas API
 * This is the API for all your needs SKI core data<br/><br/>Atlas serves the following applications:<br/>line-directory:1.11.0-SNAPSHOT<br/>business-organisation-directory:1.11.0-SNAPSHOT<br/>user-administration:1.11.0-SNAPSHOT<br/>
 *
 * The version of the OpenAPI document: 1.11.0-SNAPSHOT
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Status } from './status';

export interface TimetableFieldNumberVersion {
  /**
   * Technical identifier
   */
  id?: number;
  /**
   * Timetable field number identifier
   */
  readonly ttfnid?: string;
  /**
   * Description
   */
  description?: string;
  /**
   * Number
   */
  number: string;
  /**
   * Timetable field number
   */
  swissTimetableFieldNumber: string;
  status?: Status;
  /**
   * Date - valid from
   */
  validFrom: Date;
  /**
   * Date - valid to
   */
  validTo: Date;
  /**
   * Business organisation
   */
  businessOrganisation: string;
  /**
   * Additional comment
   */
  comment?: string;
  /**
   * Optimistic locking version - instead of ETag HTTP Header (see RFC7232:Section 2.3)
   */
  etagVersion?: number;
}
