/**
 * Atlas API
 * This is the API for all your needs with SKI core data.<br/><br/>Atlas serves the following applications:<br/><ul><li>line-directory<br/>RestDoc: <a href=\'https://line-directory.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://line-directory.local.app.sbb.ch/static/rest-api.html</a></li><li>service-point-directory<br/>RestDoc: <a href=\'https://service-point-directory.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://service-point-directory.local.app.sbb.ch/static/rest-api.html</a></li><li>business-organisation-directory<br/>RestDoc: <a href=\'https://business-organisation-directory.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://business-organisation-directory.local.app.sbb.ch/static/rest-api.html</a></li><li>workflow<br/>RestDoc: <a href=\'https://workflow.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://workflow.local.app.sbb.ch/static/rest-api.html</a></li><li>export-service-point<br/>RestDoc: <a href=\'https://export-service-point.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://export-service-point.local.app.sbb.ch/static/rest-api.html</a></li><li>user-administration<br/>RestDoc: <a href=\'https://user-administration.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://user-administration.local.app.sbb.ch/static/rest-api.html</a></li><li>import-service-point<br/>RestDoc: <a href=\'https://import-service-point.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://import-service-point.local.app.sbb.ch/static/rest-api.html</a></li><li>prm-directory<br/>RestDoc: <a href=\'https://prm-directory.local.app.sbb.ch/static/rest-api.html\' target=\'_blank\'>https://prm-directory.local.app.sbb.ch/static/rest-api.html</a></li></ul><br/>Atlas gets updated with the following features: <a href=\'https://atlas-info.app.sbb.ch/static/atlas-release-notes.html\' target=\'_blank\'>Atlas Release Notes</a>
 *
 * The version of the OpenAPI document: 2.227.0
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Status } from './status';
import { TimetableHearingStatementDocument } from './timetableHearingStatementDocument';
import { TimetableHearingStatementSender } from './timetableHearingStatementSender';
import { SwissCanton } from './swissCanton';
import { StatementStatus } from './statementStatus';
import { TimetableHearingStatementResponsibleTransportCompany } from './timetableHearingStatementResponsibleTransportCompany';


/**
 * Deprecated in favor of TimetableHearingStatementV2
 */
export interface TimetableHearingStatement { 
    /**
     * Object creation date
     */
    readonly creationDate?: string;
    /**
     * User creator
     */
    readonly creator?: string;
    /**
     * Last edition date
     */
    readonly editionDate?: string;
    /**
     * User editor
     */
    readonly editor?: string;
    status?: Status;
    /**
     * Technical identifier
     */
    readonly id?: number;
    /**
     * TimetableYear
     */
    timetableYear?: number;
    statementStatus?: StatementStatus;
    /**
     * TimetableFieldNumberId regarding the statement
     */
    ttfnid?: string;
    /**
     * Timetable field number
     */
    timetableFieldNumber?: string;
    /**
     * Timetable field number description
     */
    timetableFieldDescription?: string;
    swissCanton: SwissCanton;
    oldSwissCanton?: SwissCanton;
    /**
     * StopPlace information for the statement
     */
    stopPlace?: string;
    responsibleTransportCompanies?: Array<TimetableHearingStatementResponsibleTransportCompany>;
    /**
     * Comma separated Transport Companies abbreviation
     */
    readonly responsibleTransportCompaniesDisplay?: string;
    /**
     * Statement of citizen
     */
    statement: string;
    /**
     * List of uploaded documents
     */
    documents?: Array<TimetableHearingStatementDocument>;
    /**
     * Statement of Federal office of transport
     */
    justification?: string;
    /**
     * Statement comment
     */
    comment?: string;
    /**
     * Optimistic locking version - instead of ETag HTTP Header (see RFC7232:Section 2.3)
     */
    etagVersion?: number;
    statementSender: TimetableHearingStatementSender;
}

