/**
 * Atlas API
 * This is the API for all your needs SKI core data<br/><br/>Atlas serves the following applications:<br/>line-directory:1.35.0-SNAPSHOT<br/>business-organisation-directory:1.35.0-SNAPSHOT<br/>user-administration:1.35.0-SNAPSHOT<br/>
 *
 * The version of the OpenAPI document: 1.35.0-SNAPSHOT
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Status } from './status';

export interface TimetableFieldNumber {
  /**
   * Timetable field number
   */
  swissTimetableFieldNumber: string;
  /**
   * Number
   */
  number: string;
  /**
   * Timetable field number identifier
   */
  ttfnid?: string;
  /**
   * Description
   */
  description?: string;
  status: Status;
  /**
   * BusinessOrganisation SBOID
   */
  businessOrganisation: string;
  /**
   * Date - valid from
   */
  validFrom: Date;
  /**
   * Date - valid to
   */
  validTo: Date;
}
