/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TimetableHearingStatementDocument { 
    /**
     * Technical identifier
     */
    readonly id?: number;
    /**
     * FileName of uploaded document
     */
    readonly fileName: string;
    /**
     * Content length
     */
    readonly fileSize: number;
}

