/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BusinessOrganisation } from './businessOrganisation';


export interface TransportCompanyBoRelation { 
    /**
     * Transport Company Relation Id
     */
    id?: number;
    businessOrganisation?: BusinessOrganisation;
    /**
     * Valid From
     */
    validFrom?: Date;
    /**
     * Valid To
     */
    validTo?: Date;
}

