/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateTransportCompanyRelation { 
    /**
     * id
     */
    id?: number;
    /**
     * Valid From
     */
    validFrom?: Date;
    /**
     * Valid To
     */
    validTo?: Date;
}

