/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserAccountStatus } from './userAccountStatus';
import { Permission } from './permission';


export interface User { 
    /**
     * SBB User Id
     */
    sbbUserId?: string;
    /**
     * User lastname
     */
    lastName?: string;
    /**
     * User firstname
     */
    firstName?: string;
    /**
     * User E-Mail address
     */
    mail?: string;
    /**
     * User display name (azure)
     */
    displayName?: string;
    accountStatus?: UserAccountStatus;
    /**
     * User permissions
     */
    permissions?: Set<Permission>;
    userId?: string;
}
export namespace User {
}


