/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Permission } from './permission';


export interface UserPermissionCreate { 
    /**
     * User permissions
     */
    permissions: Array<Permission>;
    /**
     * SBB User-ID
     */
    sbbUserId: string;
}

