/**
 * Atlas API
 * This is the API for all your needs SKI core data<br/><br/>Atlas serves the following applications:<br/>line-directory:1.108.0<br/>business-organisation-directory:1.108.0<br/>workflow:1.108.0<br/>user-administration:1.108.0<br/>
 *
 * The version of the OpenAPI document: 1.108.0
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Person } from './person';

export interface Workflow {
  /**
   * Business Object Id: the generated DB id
   */
  businessObjectId: number;
  /**
   * Swiss Id: the generated DB id
   */
  swissId: string;
  /**
   * Workflow Type
   */
  workflowType: Workflow.WorkflowTypeEnum;
  description: string;
  /**
   * Workflow Status
   */
  readonly workflowStatus?: Workflow.WorkflowStatusEnum;
  workflowComment?: string;
  checkComment?: string;
  client?: Person;
  examinant?: Person;
  /**
   * Object creation date
   */
  readonly creationDate?: string;
  /**
   * Last edition date
   */
  readonly editionDate?: string;
}
export namespace Workflow {
  export type WorkflowTypeEnum = 'LINE' | 'SUBLINE';
  export const WorkflowTypeEnum = {
    Line: 'LINE' as WorkflowTypeEnum,
    Subline: 'SUBLINE' as WorkflowTypeEnum,
  };
  export type WorkflowStatusEnum =
    | 'ADDED'
    | 'STARTED'
    | 'REVISION'
    | 'HEARING'
    | 'APPROVED'
    | 'REJECTED';
  export const WorkflowStatusEnum = {
    Added: 'ADDED' as WorkflowStatusEnum,
    Started: 'STARTED' as WorkflowStatusEnum,
    Revision: 'REVISION' as WorkflowStatusEnum,
    Hearing: 'HEARING' as WorkflowStatusEnum,
    Approved: 'APPROVED' as WorkflowStatusEnum,
    Rejected: 'REJECTED' as WorkflowStatusEnum,
  };
}
