import { ReadServicePointVersion } from '../../api';

export const BERN_WYLEREGG: ReadServicePointVersion = {
  creationDate: '2021-03-22T09:26:29',
  creator: 'fs45117',
  editionDate: '2022-02-23T17:10:10',
  editor: 'fs45117',
  id: 1000,
  sloid: 'ch:1:sloid:89008',
  designationLong: undefined,
  designationOfficial: 'Bern, Wyleregg',
  abbreviation: undefined,
  operatingPoint: true,
  operatingPointWithTimetable: true,
  freightServicePoint: false,
  sortCodeOfDestinationStation: undefined,
  businessOrganisation: 'ch:1:sboid:100626',
  categories: [],
  operatingPointType: undefined,
  operatingPointTechnicalTimetableType: undefined,
  operatingPointTrafficPointType: undefined,
  operatingPointRouteNetwork: false,
  meansOfTransport: ['BUS'],
  stopPointType: undefined,
  servicePointGeolocation: {
    spatialReference: 'LV95',
    lv95: { north: 1201099.0, east: 2600783.0 },
    wgs84: { north: 46.96096808019183, east: 7.448919722210132 },
    wgs84web: { north: 5935705.395163289, east: 829209.9504364047 },
    height: 555.0,
    swissLocation: {
      canton: 'BERN',
      cantonInformation: { fsoNumber: 2, name: 'Bern', abbreviation: 'BE' },
      district: { fsoNumber: 246, districtName: 'Bern-Mittelland' },
      localityMunicipality: { fsoNumber: 351, municipalityName: 'Bern', localityName: 'Bern' },
    },
    isoCountryCode: 'CH',
  },
  status: 'VALIDATED',
  validFrom: new Date('2014-12-14'),
  validTo: new Date('2021-03-31'),
  etagVersion: 0,
  number: { number: 8589008, checkDigit: 7, uicCountryCode: 85, numberShort: 89008 },
  categoriesInformation: [],
  operatingPointTypeInformation: undefined,
  operatingPointTechnicalTimetableTypeInformation: undefined,
  operatingPointTrafficPointTypeInformation: undefined,
  meansOfTransportInformation: [
    {
      code: 'B',
      designationDe: 'Bus',
      designationFr: 'Bus',
      designationIt: 'Bus',
      designationEn: 'Bus',
    },
  ],
  stopPointTypeInformation: undefined,
  operatingPointKilometerMaster: undefined,
  operatingPointKilometer: false,
  stopPoint: true,
  fareStop: false,
  trafficPoint: true,
  borderPoint: false,
  hasGeolocation: true,
};
