export enum ServicePointIconType {
  OPERATING_POINT_TECHNICAL = 'OPERATING_POINT_TECHNICAL',
  STOP_POINT_AND_FREIGHT_SERVICE_POINT = 'STOP_POINT_AND_FREIGHT_SERVICE_POINT',
  STOP_POINT = 'STOP_POINT',
  FREIGHT_SERVICE_POINT = 'FREIGHT_SERVICE_POINT',
  SERVICE_POINT = 'SERVICE_POINT',
}
