export enum ServicePointIconType {
  STOP_POINT_AND_FREIGHT_SERVICE_POINT = 'STOP_POINT_AND_FREIGHT_SERVICE_POINT',
  OPERATING_POINT_TECHNICAL = 'OPERATING_POINT_TECHNICAL',
  SERVICE_POINT = 'SERVICE_POINT',
}
