/**
 * Atlas API
 * This is the API for all your needs SKI core data<br/><br/>Atlas serves the following applications:<br/>line-directory:0.46.0-SNAPSHOT<br/>timetable-field-number:0.88.0-SNAPSHOT<br/>
 *
 * The version of the OpenAPI document: 0.17.0-SNAPSHOT
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface Subline {
  /**
   * SwissSublineNumber
   */
  swissSublineNumber: string;
  /**
   * SwissLineNumber
   */
  swissLineNumber?: string;
  /**
   * Status
   */
  readonly status?: Subline.StatusEnum;
  /**
   * Subline Type
   */
  type: Subline.TypeEnum;
  /**
   * SLNID
   */
  readonly slnid?: string;
  /**
   * Description
   */
  description?: string;
  /**
   * Valid from
   */
  validFrom: Date;
  /**
   * Valid to
   */
  validTo: Date;
  /**
   * BusinessOrganisation
   */
  businessOrganisation: string;
}
export namespace Subline {
  export type StatusEnum = 'ACTIVE' | 'INACTIVE' | 'NEEDS_REVIEW' | 'IN_REVIEW' | 'REVIEWED';
  export const StatusEnum = {
    Active: 'ACTIVE' as StatusEnum,
    Inactive: 'INACTIVE' as StatusEnum,
    NeedsReview: 'NEEDS_REVIEW' as StatusEnum,
    InReview: 'IN_REVIEW' as StatusEnum,
    Reviewed: 'REVIEWED' as StatusEnum,
  };
  export type TypeEnum = 'TECHNICAL' | 'COMPENSATION';
  export const TypeEnum = {
    Technical: 'TECHNICAL' as TypeEnum,
    Compensation: 'COMPENSATION' as TypeEnum,
  };
}
