import { ReadStopPointVersion } from '../../../api';

export const STOP_POINT: ReadStopPointVersion = {
  validFrom: new Date('2014-12-14'),
  validTo: new Date('2021-03-31'),
  number: {
    number: 8589008,
    checkDigit: 7,
    uicCountryCode: 85,
    numberShort: 89008,
  },
  sloid: 'ch:1:sloid:89008',
  url: 'www.sbb.ch',
  meansOfTransport: ['BUS'],
  alternativeTransport: 'TO_BE_COMPLETED',
  assistanceAvailability: 'TO_BE_COMPLETED',
  assistanceRequestFulfilled: 'TO_BE_COMPLETED',
  assistanceService: 'TO_BE_COMPLETED',
  audioTicketMachine: 'TO_BE_COMPLETED',
  dynamicAudioSystem: 'TO_BE_COMPLETED',
  dynamicOpticSystem: 'TO_BE_COMPLETED',
  ticketMachine: 'TO_BE_COMPLETED',
  visualInfo: 'TO_BE_COMPLETED',
  wheelchairTicketMachine: 'TO_BE_COMPLETED',
  creationDate: '2020-01-01',
  creator: 'Cianni',
  reduced: true,
  editionDate: '2020-01-05',
  editor: 'Nicola',
  recordingObligation: true,
};
export const STOP_POINT_COMPLETE: ReadStopPointVersion = {
  validFrom: new Date('2014-12-14'),
  validTo: new Date('2021-03-31'),
  number: {
    number: 8589008,
    checkDigit: 7,
    uicCountryCode: 85,
    numberShort: 89008,
  },
  sloid: 'ch:1:sloid:89008',
  url: 'www.sbb.ch',
  meansOfTransport: ['TRAIN'],
  alternativeTransport: 'TO_BE_COMPLETED',
  assistanceAvailability: 'TO_BE_COMPLETED',
  assistanceRequestFulfilled: 'TO_BE_COMPLETED',
  assistanceService: 'TO_BE_COMPLETED',
  audioTicketMachine: 'TO_BE_COMPLETED',
  dynamicAudioSystem: 'TO_BE_COMPLETED',
  dynamicOpticSystem: 'TO_BE_COMPLETED',
  ticketMachine: 'TO_BE_COMPLETED',
  visualInfo: 'TO_BE_COMPLETED',
  wheelchairTicketMachine: 'TO_BE_COMPLETED',
  creationDate: '2020-01-01',
  creator: 'Cianni',
  reduced: false,
  editionDate: '2020-01-05',
  editor: 'Nicola',
<<<<<<< HEAD
=======
  recordingObligation: true,
>>>>>>> 6f0ccd477 (ATLAS-2670: reformat code)
};
