-- copied from org\springframework\batch\core\migration\5.0\migration-postgresql.sql
ALTER TABLE BATCH_JOB_EXECUTION DROP COLUMN JOB_CONFIGURATION_LOCATION;

ALTER TABLE BATCH_STEP_EXECUTION ADD CREATE_TIME TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:00';
ALTER TABLE BATCH_STEP_EXECUTION ALTER COLUMN START_TIME DROP NOT NULL;

ALTER TABLE BATCH_JOB_EXECUTION_PARAMS DROP COLUMN DATE_VAL;
ALTER TABLE BATCH_JOB_EXECUTION_PARAMS DROP COLUMN LONG_VAL;
ALTER TABLE BATCH_JOB_EXECUTION_PARAMS DROP COLUMN DOUBLE_VAL;

ALTER TABLE BATCH_JOB_EXECUTION_PARAMS
    rename COLUMN TYPE_CD to PARAMETER_TYPE;
ALTER TABLE BATCH_JOB_EXECUTION_PARAMS
    alter COLUMN PARAMETER_TYPE type VARCHAR(100);

ALTER TABLE BATCH_JOB_EXECUTION_PARAMS
    rename COLUMN KEY_NAME to PARAMETER_NAME;
ALTER TABLE BATCH_JOB_EXECUTION_PARAMS
    alter COLUMN PARAMETER_NAME type VARCHAR(100);

ALTER TABLE BATCH_JOB_EXECUTION_PARAMS
    rename COLUMN STRING_VAL to PARAMETER_VALUE;
ALTER TABLE BATCH_JOB_EXECUTION_PARAMS
    alter COLUMN PARAMETER_VALUE type VARCHAR(2500);

DELETE
FROM BATCH_STEP_EXECUTION_CONTEXT;
DELETE
FROM BATCH_STEP_EXECUTION;
DELETE
FROM BATCH_JOB_EXECUTION_CONTEXT;
DELETE
FROM BATCH_JOB_EXECUTION_PARAMS;
DELETE
FROM BATCH_JOB_EXECUTION;
DELETE
FROM BATCH_JOB_INSTANCE;