package ch.sbb.atlas.kafka.model.mail;

import lombok.Getter;

@Getter
public enum MailType {

  ATLAS_STANDARD,
  TU_IMPORT,
  SCHEDULING_ERROR_NOTIFICATION,

  IMPORT_SERVICE_POINT_ERROR_NOTIFICATION,
  IMPORT_SERVICE_POINT_SUCCESS_NOTIFICATION,
  EXPORT_SERVICE_POINT_ERROR_NOTIFICATION,
  WORKFLOW_NOTIFICATION,

  START_STOP_POINT_WORKFLOW_EXAMINANT_NOTIFICATION,
  START_STOP_POINT_WORKFLOW_CC_NOTIFICATION,
  REJECT_STOP_POINT_WORKFLOW_NOTIFICATION,
  STOP_POINT_WORKFLOW_PINCODE_NOTIFICATION,
  APPROVED_STOP_POINT_WORKFLOW_NOTIFICATION,
  CANCEL_STOP_POINT_WORKFLOW_NOTIFICATION,
  STOP_POINT_WORKFLOW_RESTART_NOTIFICATION,
  STOP_POINT_WORKFLOW_RESTART_CC_NOTIFICATION,

}
