package ch.sbb.atlas.kafka.model.mail;

import lombok.Getter;

@Getter
public enum MailType {

  ATLAS_STANDARD,
  TU_IMPORT,
  SCHEDULING_ERROR_NOTIFICATION,

  UPDATE_GEOLOCATION_ERROR_NOTIFICATION,
  UPDATE_GEOLOCATION_SUCCESS_NOTIFICATION,
  EXPORT_SERVICE_POINT_ERROR_NOTIFICATION,

  // Line Approval Workflow
  LINE_STARTED_WORKFLOW_NOTIFICATION,
  LINE_APPROVED_WORKFLOW_NOTIFICATION,
  LINE_REJECTED_WORKFLOW_NOTIFICATION,

  // StopPoint Designation Approval Workflow
  START_STOP_POINT_WORKFLOW_EXAMINANT_NOTIFICATION,
  START_STOP_POINT_WORKFLOW_CC_NOTIFICATION,
  REJECT_STOP_POINT_WORKFLOW_NOTIFICATION,
  STOP_POINT_WORKFLOW_PINCODE_NOTIFICATION,
  APPROVED_STOP_POINT_WORKFLOW_NOTIFICATION,
  CANCEL_STOP_POINT_WORKFLOW_NOTIFICATION,
  STOP_POINT_WORKFLOW_RESTART_NOTIFICATION,
  STOP_POINT_WORKFLOW_RESTART_CC_NOTIFICATION,

  // BulkImport
  BULK_IMPORT_RESULT_NOTIFICATION,

  // StopPoint Termination Workflow
  START_TERMINATION_STOP_POINT_WORKFLOW_NOTIFICATION,
  TARIFF_STOP_NOT_APPROVED_NOTIFICATION,
  TARIFF_STOP_APPROVED_NOTIFICATION,
  ABORT_TERMINATION_NOTIFICATION,
  STOP_POINT_TERMINATION_CONFIRMED_NOTIFICATION,

}
