package ch.sbb.exportservice.model;

public enum ExportObjectV1 {

  SERVICE_POINT_VERSION,
  TRAFFIC_POINT_ELEMENT_VERSION,
  LOADING_POINT_VERSION,
  STOP_POINT_VERSION,
  PLATFORM_VERSION,
  REFERENCE_POINT_VERSION,
  CONTACT_POINT_VERSION,
  TOILET_VERSION,
  PARKING_LOT_VERSION,
  RELATION_VERSION

}
