### get lines
GET {{host-line-directory}}/v1/lines
Authorization: Bearer {{access_token}}

### get lines by slnid
GET {{host-line-directory}}/v1/lines/{{testSlnid}}
Authorization: Bearer {{access_token}}

### delete lines version by id
DELETE {{host-line-directory}}/v1/lines/version/{{testId}}
Authorization: Bearer {{access_token}}
